/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Grégory' at '02/02/16 15:20' with Gradle 2.10
 *
 * @author Grégory, @date 02/02/16 15:20
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
